#!/bin/bash

# Check if the arguments are not correct
if [ "$#" -ne 3 ]; then
    echo -e "${RED}Usage: $0 <wordlist> <scanner> <ip-address>${NC}"
    echo -e "${RED}Available scanners: ffuf, dirsearch, gobuster${NC}"
    exit 1
fi

WORDLIST="$1"
SCANNER="$2"
IP_ADDRESS="$3"

OUTPUT_DIR="fuzzing"

RED='\e[31m'
GREEN='\e[32m'
YELLOW='\e[33m'
NC='\e[0m'

# Check if the output directory exists
if [ -d "$OUTPUT_DIR" ]; then
    echo -e "${YELLOW}Output directory already exists. Results will be appended to existing files.${NC}"
else
    mkdir -p "$OUTPUT_DIR"
    echo -e "${GREEN}Output directory created: $OUTPUT_DIR${NC}"
fi

# Function to run Dirsearch
run_dirsearch() {
    echo -e "${GREEN}Running Dirsearch...${NC}"
    dirsearch -u "http://$IP_ADDRESS" -e html,jsp,php,asp,aspx -t 10 -o "$OUTPUT_DIR/dirsearch_results.txt" --format=plain -x 403,404,401,400
    echo -e "${GREEN}Command used: dirsearch -u http://$IP_ADDRESS -e * -t 10 -o $OUTPUT_DIR/dirsearch_results.txt --format=plain -x 403,404,401,400${NC}"
}

# Function to run FFUF
run_ffuf() {
    echo -e "${GREEN}Running FFUF...${NC}"
    ffuf -u "http://$IP_ADDRESS/FUZZ" -w "$WORDLIST" -e .asp,.aspx,.html,.jsp,.php -c -v -ic -o "$OUTPUT_DIR/ffuf_results.txt"
    echo -e "${GREEN}Command used: ffuf -u http://$IP_ADDRESS/FUZZ -w $WORDLIST -c -v -ic -o $OUTPUT_DIR/ffuf_results.txt${NC}"
}

# Function to run Gobuster
run_gobuster() {
    echo -e "${GREEN}Running Gobuster...${NC}"
    gobuster dir -u "http://$IP_ADDRESS" -w "$WORDLIST" -qnkx '.asp,.aspx,.html,.jsp,.php' -o "$OUTPUT_DIR/gobuster_results.txt"
    echo -e "${GREEN}Command used: gobuster dir -u http://$IP_ADDRESS -w $WORDLIST -o $OUTPUT_DIR/gobuster_results.txt${NC}"
}

# Select the scanner based on the argument
case $SCANNER in
    dirsearch)
        run_dirsearch
        ;;
    ffuf)
        run_ffuf
        ;;
    gobuster)
        run_gobuster
        ;;
    *)
        echo -e "${RED}Invalid scanner. Please choose from: ffuf, dirsearch, gobuster${NC}"
        exit 1
        ;;
esac

echo -e "${GREEN}Scanning complete.${NC}"