#!/bin/bash
# Automate running python server tools for Linux enum
# Don't forget to change your Linux Tools for PE or anything else
cd /home/wayman/Tools/Linux || { echo "Directory not found!"; exit 1; }

ls
    
port=${1:-80}

echo -e "\n==================================="
echo " Starting HTTP Server on Port: $port"
echo "==================================="

python3 -m http.server "$port" 